# Generated by Django 5.1.1 on 2026-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("lmstudio", "LM Studio (Local)"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=500)),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        help_text="Custom API base URL (for LM Studio, etc.)",
                        max_length=500,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, help_text="Preferred model name", max_length=200
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider"],
            },
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-updated_at"]},
        ),
    ]
